controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    # config/routes.yaml
admin_import_csv:
        path: /admin/import-csv
        controller: App\Controller\Admin\MyEasyAdminController::importCsvAction

